version: "3"
services:
    parse-server:
        build: ./parse-server
        depends_on:
          - db
        networks:
            - server
        ports:
            - "1337:1337"
        env_file: ./parse-server.env
    db:
        image: mongo
        volumes:
            - ./data:/data/db
        networks:
            - server
    # front:
    #     image: node:9.2.0-slim
    #     depends_on:
    #         - parse-server
    #     user: "node"
    #     working_dir: /home/node/app
    #     volumes:
    #         - ./front:/home/node/app
    #     networks:
    #         - server
    #     ports:
    #         - "8080:8080"
    #         - "80:80"
    #     command: "npm run dev"

networks:
    server:
